### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by nzlosh** [nzlosh/err-backend-slackv3#1]
@duhow @agarfu

I've moved the slackv3 backend out of the errbot tree to try and accelerate the development process.  I've invited you both to be collaborators in this project since you're both actively working on Slack Events support.  I think it would be great if we can combine our efforts here and eventually propose a merge to errbot once the backend is stable.

**Comment by duhow** [comment]
Sounds good! :)

**Comment by nzlosh** [comment]
Thanks for pitching in with the project, I'll close this issue now that the ball is rolling.
