### ISSUE TITLE
Unable to receive messages from slack.

### ISSUE THREAD

**Issue by sanandan** [nzlosh/err-backend-slackv3#26]
Hi Team,
I'm not able to receive commands from slack even though the log show the connection is successfully established.
PLease let know if you need any debug logs.

Successful connection log:
####################

`21:17:44 INFO     slack_sdk.socket_mode.bui A new session has been established (session id: 88436168-824f-4743-a3cf-84dc3f67d5ee)
21:17:44 DEBUG    errbot.backends.slackv3   Initialised, waiting for events.
21:17:44 INFO     slack_sdk.socket_mode.bui Starting to receive messages from a new connection (session id: 88436168-824f-4743-a3cf-84dc3f67d5ee)
21:17:44 DEBUG    slack_sdk.socket_mode.bui on_message invoked: (message: {"type":"hello","num_connections":1,"debug_info":{"host":"applink-d85c5c684-fgz8q","build_number":18,"approximate_connection_time":18060},"connection_info":{"app_id":"A0195UU34LW"}})
21:17:44 DEBUG    slack_sdk.socket_mode.bui A new message enqueued (current queue size: 1)
21:17:44 DEBUG    slack_sdk.socket_mode.bui A message dequeued (current queue size: 0)
21:17:44 DEBUG    slack_sdk.socket_mode.bui Message processing started (type: hello, envelope_id: None)
21:17:44 DEBUG    errbot.backends.slackv3   message listeners : [<bound method SlackBackend._sm_handle_hello of <errbot.backends.slackv3.SlackBackend object at 0x1061f6b70>>]
` 
###################

**Comment by nzlosh** [comment]
Hello,

The log shows the slack backend is receiving events from slack without any errors.

The bot responds to commands, if you're using a default configuration try issuing the `!help` command.  I'd also recommend you take the time to read over the documentation to familiarise yourself with errbot https://errbot.readthedocs.io/en/latest/#user-guide.

**Comment by sanandan** [comment]
Sorry my bad, i jumped the gun. Issue was because i had not subscribed for the events. Once i enabled event subscriptions in slack apps page i'm able to receive the messages. I had only generated the app token and thought it was sufficient.
